# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [5]:
import numpy as np
import sympy as sp
from numpy import linalg
from google.colab import files
import pandas as pd

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку.
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+5z=10
\end{matrix}
\right.
$$

In [6]:
# Составляем массив, решаем через solve и делаем проверку.
A = np.array([[-1, 5, -3],
              [4, -1, 5],
              [3, 4, 5]])
b = np.array([8, -1, 10])
X = linalg.solve(A, b)
print(f'Решение СЛАУ: {X}')
print(f'Проверка: {np.allclose(A @ X, b)}')

Решение СЛАУ: [-1.  2.  1.]
Проверка: True


### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместна ли СЛАУ
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+2z=7
\end{matrix}
\right.
$$

Сделать вывод о числе решений (текстом)

In [7]:
# Составляем массив, находим определитель, ранк левой части и расширенной матрицы.
A = np.array([[-1, 5, -3],
              [4, -1, 5],
              [3, 4, 2]])
b = np.array([8, -1, 7])
rank_A = linalg.matrix_rank(A)
rank_Ab = linalg.matrix_rank(np.column_stack((A, b)))
det_A = linalg.det(A)
print(f'Ранг rg(А) = {rank_A}, ранг расширенной матрицы rb(A | b) = {rank_Ab}.')
print(f'Определитель |А| = {det_A}')

if rank_A == rank_Ab:
  if det_A != 0:
    print('Система имеет единственное решение.')
  else:
    print('Система имеет бесконечно много решений.')
else:
  print('Система не имеет решений.')

Ранг rg(А) = 2, ранг расширенной матрицы rb(A | b) = 2.
Определитель |А| = 0.0
Система имеет бесконечно много решений.


### Задание 3
В расширенной матрице СЛАУ из Задания 2

1) выделить матрицу левой части

2) выделить столбец правой части

3) транспонировать матрицу, полученную в 1)

4) получить расширенную матрицу из матрицы 3) и столбца 2)

5) создать на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел 1 и $-1$.

In [8]:
matrixQ = np.array([[-1, 5, -3, 8],
                    [4, -1, 5, -1],
                    [3, 4, 2, 7]])

Q_transpose = np.transpose(matrixQ)
A = np.transpose(Q_transpose[:-1])
b = Q_transpose[-1]
C = np.transpose(A)
D = np.array([[(-1)**(i + j) for i in range(4)] for j in range(3)])
print(f'1. Матрица левой части: \n{A}\n')
print(f'2. Столбец правой части: \n{b}\n')
print(f'3. Транспонированная левая часть: \n{C}\n')
print(f'4. Расширенная матрица из транспонированной левой части и столбца правой: \n{np.column_stack((C, b))}\n')
print(f'5. Матрица 3×4 из чисел 1 и -1 в шахматном порядке: \n{D}\n')

1. Матрица левой части: 
[[-1  5 -3]
 [ 4 -1  5]
 [ 3  4  2]]

2. Столбец правой части: 
[ 8 -1  7]

3. Транспонированная левая часть: 
[[-1  4  3]
 [ 5 -1  4]
 [-3  5  2]]

4. Расширенная матрица из транспонированной левой части и столбца правой: 
[[-1  4  3  8]
 [ 5 -1  4 -1]
 [-3  5  2  7]]

5. Матрица 3×4 из чисел 1 и -1 в шахматном порядке: 
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]



### Задание 4.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=-1$, $a=0$ и $a=1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$
**Указание** - описать функцию check_SLAE от аргументов $A$ и $b$ (матрица левой части и столбец правой части), которая возвращает 0 для несовместной СЛАУ, 1 для совместной СЛАУ с единственным решением и 2 в остальных случаях.

Затем в цикле по значениям параметра $a$ проверять с помощью check_SLAE совместность и единственность решения СЛАУ и выводить на экран значение параметра и решение СЛАУ, если оно существует и единственно или "решений нет" или "решение не единственно".

In [31]:
# Составляем массив СЛАУ и создаём параметр a.
a = sp.Symbol('a')
A = np.array([[-1, 5, -3],
              [4, -a, 5],
              [3, 4, 2]])
b = np.array([[8*a, -a, 5*a]])

# Функция, которая проверяет совместность СЛАУ, сравнивая ранги основной и расширенной матрицы.
def check_SLAE(A, b):
  rank_A = linalg.matrix_rank(A)
  rank_Ab = linalg.matrix_rank(np.column_stack((A, b)))
  if rank_A != rank_Ab:
    return 0
  return 1

# Функция, которая подставляет значения параметра.
# Проходим по каждому элементу и смотрим, есть ли в нём параметр.
# Если есть, то разбиваем элемент на коэффициент и параметр по знаку умножения (*).
# Если количество элементов после разбивки равно 1 (т.е. есть только параметр),
# то смотрим, есть ли перед ним знак минуса.
# Иначе, умножаем коэффициент на параметр.
# Составляем строку и массив с данным параметром и возвращаем.
def Subs(array, par):
  new_array = []
  for line in array:
    new_line = []
    for el in line:
      if 'a' in str(el):
        # Работаем при условии, что элемент записан в виде x * a,
        # где a - параметр; x - коэффициент.
        # Иначе надо преобразовать эту функцию.
        items = str(el).split('*')
        if len(items) == 1:
          if str(el)[0] == '-':
            el = -1 * par
          else:
            el = par
        else:
          el = int(items[0]) * par
      new_line.append(el)
    new_array.append(new_line)
  return np.array(new_array)

# Каждое данное значение параметра подставляем в СЛАУ,
# проверяем на совместность и выводим ответ.
params = (-1, 0, 1)
for par in params:
  new_A = Subs(A, par)
  new_b = np.transpose(Subs(b, par))
  print(f'При a = {par}:')
  if check_SLAE(new_A, new_b):
    if linalg.det(new_A):
      sol = linalg.solve(new_A, new_b)
      print(*sol)
      print(f'Проверка: {np.allclose(new_A @ sol, new_b)}')
    else:
      print('решение не единственно')
  else:
    print('решений нет')
  print()

При a = -1:
[-1.28571429] [-1.] [1.42857143]
Проверка: True

При a = 0:
[0.] [0.] [-0.]
Проверка: True

При a = 1:
решений нет



### Задание 5.
Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

Решить СЛАУ $AX=b$ и вывести полученное решение на экран.

Записать полученное решение в файл  'SLAE_5.xlsx' на лист 'X5'.

Скачать полученный файл.

In [36]:
# Скачиваем файл.
uploaded = files.upload()
for file_name in uploaded.keys():
    print(f'Загружен файл {file_name}')

# Считываем правую и левую части СЛАУ.
Adf = pd.read_excel(file_name, sheet_name='A5', header=None)
bdf = pd.read_excel(file_name, sheet_name='b5', header=None)
# Вывод правой и левой части СЛАУ.
print(Adf, bdf, sep='\n\n')

# Выделяем матрицу A и столбец b.
A = Adf.to_numpy()
b = bdf.to_numpy()

# Решаем СЛАУ и выводим решение.
X = linalg.solve(A, b)
print('\nРешение: ', *X.T)

# Записываем полученное решение в файл.
Xdf = pd.DataFrame(X)
with pd.ExcelWriter(file_name, mode='a') as writer:
    Xdf.to_excel(writer, sheet_name='X5', header=False, index=False)

# Скачиваем полученный файл.
files.download(file_name)

Saving SLAE_5.xlsx to SLAE_5.xlsx
Загружен файл SLAE_5.xlsx
    0  1  2  3
0   6 -3 -1  8
1  -9 -7 -5  9
2   0 -6  5  4
3 -21 -1 -7 -7

    0
0 -15
1 -42
2 -34
3 -44

Решение:  [-4.7 18.8  8.   9.7]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.

На листы 'A1', 'A2' и т.п. файла 'Name_Ind_8_SLAE.xlsx' записать матрицы при заданных значениях параметра $a$, на листы 'b1', 'b2' и т.п. столбцы правой части СЛАУ, на листы 'X1', 'X2' и т.п. решения СЛАУ (если оно существует!).


N 23
\begin{align*}
 A = \left[\begin{matrix}-6 & 6 & -7 & -6\\4 & a & 1 & -7\\-6 & -8 & -8 & 6\\-22 & -24 & -12 & 34\end{matrix}\right],
    \qquad b = \left[\begin{matrix}-20\\45\\-110\\-250\end{matrix}\right], \alpha = 0, \alpha = 4, \alpha = 6.
 \end{align*}

In [34]:
# Действия аналогично заданию 4.

a = sp.Symbol('a')
A = np.array([[-6, 6, -7, -6],
              [4, a, 1, -7],
              [-6, -8, -8, 6],
              [-22, -24, -12, 34]])
b = np.array([[-20, 45, -110, -250]])

# Функция, которая проверяет совместность СЛАУ, сравнивая ранги основной и расширенной матрицы.
def check_SLAE(A, b):
  rank_A = linalg.matrix_rank(A)
  rank_Ab = linalg.matrix_rank(np.column_stack((A, b)))
  if rank_A != rank_Ab:
    return 0
  return 1

def Subs(array, par):
  new_array = []
  for line in array:
    new_line = []
    for el in line:
      if 'a' in str(el):
        # Работаем при условии, что элемент записан в виде x * a,
        # где a - параметр; x - коэффициент.
        items = str(el).split('*')
        if len(items) == 1:
          if str(el)[0] == '-':
            el = -1 * par
          else:
            el = par
        else:
          el = int(items[0]) * par
      new_line.append(el)
    new_array.append(new_line)
  return np.array(new_array)

# Составляем список массивов A, B, X, чтобы потом их записать в таблицу.
all_A = []
all_B = []
all_X = []
# number = 0
for par in (0, 4, 6):
  number += 1
  new_A = Subs(A, par)
  new_B = np.transpose(Subs(b, par))
  all_A.append(new_A)
  all_B.append(new_B)
  print(f'При a = {par}:')
  if check_SLAE(new_A, new_B):
    if linalg.det(new_A):
      sol = linalg.solve(new_A, new_B)
      print(*sol)
      print(f'Проверка: {np.allclose(new_A @ sol, new_B)}')
    else:
      sol = 'б/м решений'
      print(sol)
  else:
    sol = ['решений нет']
    print('решений нет')
  all_X.append(sol)
  print()

file_name = 'Name_Ind_8_SLAE.xlsx'
with pd.ExcelWriter(file_name, mode='w') as writer:
  for i in range(3):
    pd.DataFrame(all_A[i]).to_excel(writer, sheet_name=f'A{i+1}', header=False, index=False)
    pd.DataFrame(all_B[i]).to_excel(writer, sheet_name=f'B{i+1}', header=False, index=False)
    pd.DataFrame(all_X[i]).to_excel(writer, sheet_name=f'X{i+1}', header=False, index=False)

При a = 0:
[-8.63636364] [-2.5] [15.90909091] [-9.09090909]
Проверка: True

При a = 4:
решений нет

При a = 6:
[-2.58379177e-15] [5.] [8.] [-1.]
Проверка: True

